# config/cucumber.yml
##YAML Template
---
android-mock: PLATFORM=android -r features/support -r features/screens/android -r features/screens/helpers -r features/screens/generics -r features/step_definitions --exclude features/ios --exclude features/support/integrado  -t ~@instrumentado --tags ~@nok
android: PLATFORM=android -r features/support -r features/screens/android -r features/screens/helpers -r features/screens/generics -r features/step_definitions --exclude features/ios  --exclude features/support/mocks -t ~@instrumentado --tags ~@nok

ios-mock: PLATFORM=ios -r features/support -r features/screens/ios -r features/screens/helpers -r features/screens/generics -r features/step_definitions --exclude features/android --exclude features/support/integrado -t ~@instrumentado --tags ~@nok
ios: PLATFORM=ios -r features/support -r features/screens/ios -r features/screens/helpers -r features/screens/generics -r features/step_definitions --exclude features/android  --exclude features/support/mocks -t ~@instrumentado --tags ~@nok

#Sugestão de tags
#--tags ~@manual --tags ~@nok --tags ~@negocio --tags ~@novo --tags ~@ios --tags ~@iOS --tags ~@integrado

